on:
  push:
    branches:
      - dev

jobs:
  migrate-d1:
    runs-on: ubuntu-latest

    steps:
      - name: Set up pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.6.2

      - uses: actions/checkout@v3

      - name: Run D1 migrations
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          command: d1 migrations apply xoxo-preview
r
